// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using be.Data;

#nullable disable

namespace be.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709020118_SeedCompleteTransactionData")]
    partial class SeedCompleteTransactionData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("be.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdminId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            PasswordHash = "admin123",
                            Username = "admin123"
                        });
                });

            modelBuilder.Entity("be.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            AdditionalNotes = "Pedas semua ya",
                            CustomerName = "Budi Santoso",
                            OrderDate = new DateTime(2026, 6, 22, 12, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-02",
                            TotalAmount = 55000m
                        },
                        new
                        {
                            OrderId = 2,
                            AdditionalNotes = "Es teh belakangan",
                            CustomerName = "Siti Rahma",
                            OrderDate = new DateTime(2026, 6, 25, 19, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-05",
                            TotalAmount = 49000m
                        },
                        new
                        {
                            OrderId = 3,
                            AdditionalNotes = "",
                            CustomerName = "Andi Wijaya",
                            OrderDate = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-01",
                            TotalAmount = 30000m
                        },
                        new
                        {
                            OrderId = 4,
                            AdditionalNotes = "Ayam paha semua",
                            CustomerName = "Dewi Lestari",
                            OrderDate = new DateTime(2026, 7, 8, 14, 20, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-09",
                            TotalAmount = 90000m
                        },
                        new
                        {
                            OrderId = 5,
                            AdditionalNotes = "Kurangi garam",
                            CustomerName = "Rian Hidayat",
                            OrderDate = new DateTime(2026, 7, 9, 8, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Pending",
                            TableNumber = "T-03",
                            TotalAmount = 27000m
                        });
                });

            modelBuilder.Entity("be.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderDetailId"));

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailId = 1,
                            Notes = "Pedas",
                            OrderId = 1,
                            Price = 25000m,
                            ProductId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            OrderDetailId = 2,
                            Notes = "",
                            OrderId = 1,
                            Price = 5000m,
                            ProductId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 3,
                            Notes = "Sedang",
                            OrderId = 2,
                            Price = 22000m,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 4,
                            Notes = "",
                            OrderId = 2,
                            Price = 30000m,
                            ProductId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 5,
                            Notes = "",
                            OrderId = 2,
                            Price = 5000m,
                            ProductId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 6,
                            Notes = "",
                            OrderId = 3,
                            Price = 30000m,
                            ProductId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 7,
                            Notes = "",
                            OrderId = 4,
                            Price = 30000m,
                            ProductId = 3,
                            Quantity = 3
                        },
                        new
                        {
                            OrderDetailId = 8,
                            Notes = "",
                            OrderId = 5,
                            Price = 22000m,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 9,
                            Notes = "",
                            OrderId = 5,
                            Price = 5000m,
                            ProductId = 4,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("be.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Makanan",
                            Description = "Nasi goreng ayam plus telur",
                            IsAvailable = true,
                            Price = 25000m,
                            ProductName = "Nasi Goreng Spesial"
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Makanan",
                            Description = "Mie goreng khas Jawa pedas manis",
                            IsAvailable = true,
                            Price = 22000m,
                            ProductName = "Mie Goreng Jawa"
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Makanan",
                            Description = "Ayam bakar bumbu madu legit",
                            IsAvailable = true,
                            Price = 30000m,
                            ProductName = "Ayam Bakar Madu"
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "Minuman",
                            Description = "Es teh manis segar",
                            IsAvailable = true,
                            Price = 5000m,
                            ProductName = "Es Teh Manis"
                        },
                        new
                        {
                            ProductId = 5,
                            Category = "Minuman",
                            Description = "Jus alpukat dengan kerokan es krim",
                            IsAvailable = true,
                            Price = 15000m,
                            ProductName = "Jus Alpukat Shaked"
                        });
                });

            modelBuilder.Entity("be.Models.OrderDetail", b =>
                {
                    b.HasOne("be.Models.Order", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("be.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("be.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
