// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using be.Data;

#nullable disable

namespace be.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709021330_ExpandFullSeedDataV2")]
    partial class ExpandFullSeedDataV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("be.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdminId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            PasswordHash = "admin123",
                            Username = "admin123"
                        });
                });

            modelBuilder.Entity("be.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            AdditionalNotes = "Pedas semua ya",
                            CustomerName = "Budi Santoso",
                            OrderDate = new DateTime(2026, 5, 3, 11, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-02",
                            TotalAmount = 50000m
                        },
                        new
                        {
                            OrderId = 2,
                            AdditionalNotes = "Minuman belakangan",
                            CustomerName = "Siti Rahma",
                            OrderDate = new DateTime(2026, 5, 8, 19, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-05",
                            TotalAmount = 65000m
                        },
                        new
                        {
                            OrderId = 3,
                            AdditionalNotes = "",
                            CustomerName = "Andi Wijaya",
                            OrderDate = new DateTime(2026, 5, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-01",
                            TotalAmount = 43000m
                        },
                        new
                        {
                            OrderId = 4,
                            AdditionalNotes = "Tidak pedas",
                            CustomerName = "Rina Oktavia",
                            OrderDate = new DateTime(2026, 5, 15, 13, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-07",
                            TotalAmount = 78000m
                        },
                        new
                        {
                            OrderId = 5,
                            AdditionalNotes = "Ekstra sambal",
                            CustomerName = "Hendra Gunawan",
                            OrderDate = new DateTime(2026, 5, 18, 18, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-03",
                            TotalAmount = 56000m
                        },
                        new
                        {
                            OrderId = 6,
                            AdditionalNotes = "",
                            CustomerName = "Mega Putri",
                            OrderDate = new DateTime(2026, 5, 22, 20, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-10",
                            TotalAmount = 48000m
                        },
                        new
                        {
                            OrderId = 7,
                            AdditionalNotes = "Kurangi gula",
                            CustomerName = "Fajar Nugroho",
                            OrderDate = new DateTime(2026, 5, 27, 10, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-04",
                            TotalAmount = 35000m
                        },
                        new
                        {
                            OrderId = 8,
                            AdditionalNotes = "Pisah tagihan",
                            CustomerName = "Laila Sari",
                            OrderDate = new DateTime(2026, 5, 30, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-08",
                            TotalAmount = 62000m
                        },
                        new
                        {
                            OrderId = 9,
                            AdditionalNotes = "Ayam paha semua",
                            CustomerName = "Doni Prasetyo",
                            OrderDate = new DateTime(2026, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-06",
                            TotalAmount = 57000m
                        },
                        new
                        {
                            OrderId = 10,
                            AdditionalNotes = "",
                            CustomerName = "Wulandari",
                            OrderDate = new DateTime(2026, 6, 7, 17, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-02",
                            TotalAmount = 46000m
                        },
                        new
                        {
                            OrderId = 11,
                            AdditionalNotes = "Tambah nasi",
                            CustomerName = "Rizky Aditya",
                            OrderDate = new DateTime(2026, 6, 11, 19, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-09",
                            TotalAmount = 85000m
                        },
                        new
                        {
                            OrderId = 12,
                            AdditionalNotes = "",
                            CustomerName = "Putri Andini",
                            OrderDate = new DateTime(2026, 6, 14, 13, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-01",
                            TotalAmount = 38000m
                        },
                        new
                        {
                            OrderId = 13,
                            AdditionalNotes = "Tidak pedas sama sekali",
                            CustomerName = "Bambang Irawan",
                            OrderDate = new DateTime(2026, 6, 18, 11, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-05",
                            TotalAmount = 70000m
                        },
                        new
                        {
                            OrderId = 14,
                            AdditionalNotes = "Ekstra keju",
                            CustomerName = "Nadia Fitriani",
                            OrderDate = new DateTime(2026, 6, 22, 20, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-03",
                            TotalAmount = 55000m
                        },
                        new
                        {
                            OrderId = 15,
                            AdditionalNotes = "",
                            CustomerName = "Surya Dharma",
                            OrderDate = new DateTime(2026, 6, 25, 12, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-07",
                            TotalAmount = 49000m
                        },
                        new
                        {
                            OrderId = 16,
                            AdditionalNotes = "Tanpa bawang",
                            CustomerName = "Intan Permata",
                            OrderDate = new DateTime(2026, 6, 28, 14, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-10",
                            TotalAmount = 41000m
                        },
                        new
                        {
                            OrderId = 17,
                            AdditionalNotes = "Manis sekali",
                            CustomerName = "Yoga Pratama",
                            OrderDate = new DateTime(2026, 6, 30, 21, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-04",
                            TotalAmount = 63000m
                        },
                        new
                        {
                            OrderId = 18,
                            AdditionalNotes = "",
                            CustomerName = "Raka Santika",
                            OrderDate = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-06",
                            TotalAmount = 52000m
                        },
                        new
                        {
                            OrderId = 19,
                            AdditionalNotes = "Ayam paha semua",
                            CustomerName = "Dewi Lestari",
                            OrderDate = new DateTime(2026, 7, 3, 12, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-02",
                            TotalAmount = 90000m
                        },
                        new
                        {
                            OrderId = 20,
                            AdditionalNotes = "Ekstra sambal",
                            CustomerName = "Arif Budiman",
                            OrderDate = new DateTime(2026, 7, 5, 19, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-08",
                            TotalAmount = 74000m
                        },
                        new
                        {
                            OrderId = 21,
                            AdditionalNotes = "",
                            CustomerName = "Sari Indah",
                            OrderDate = new DateTime(2026, 7, 7, 13, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-01",
                            TotalAmount = 33000m
                        },
                        new
                        {
                            OrderId = 22,
                            AdditionalNotes = "Level pedas sedang",
                            CustomerName = "Eko Baskoro",
                            OrderDate = new DateTime(2026, 7, 8, 18, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-09",
                            TotalAmount = 59000m
                        },
                        new
                        {
                            OrderId = 23,
                            AdditionalNotes = "Kurangi garam",
                            CustomerName = "Rian Hidayat",
                            OrderDate = new DateTime(2026, 7, 9, 8, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Lunas",
                            TableNumber = "T-05",
                            TotalAmount = 47000m
                        },
                        new
                        {
                            OrderId = 24,
                            AdditionalNotes = "Tidak mau pedas",
                            CustomerName = "Claudia Santoso",
                            OrderDate = new DateTime(2026, 7, 9, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Belum Bayar",
                            TableNumber = "T-03",
                            TotalAmount = 38000m
                        },
                        new
                        {
                            OrderId = 25,
                            AdditionalNotes = "Minta tisu banyak",
                            CustomerName = "Dimas Arya",
                            OrderDate = new DateTime(2026, 7, 9, 20, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Belum Bayar",
                            TableNumber = "T-07",
                            TotalAmount = 66000m
                        });
                });

            modelBuilder.Entity("be.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderDetailId"));

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailId = 1,
                            Notes = "Pedas",
                            OrderId = 1,
                            Price = 25000m,
                            ProductId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            OrderDetailId = 2,
                            Notes = "",
                            OrderId = 1,
                            Price = 5000m,
                            ProductId = 14,
                            Quantity = 2
                        },
                        new
                        {
                            OrderDetailId = 3,
                            Notes = "Sedang",
                            OrderId = 2,
                            Price = 22000m,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 4,
                            Notes = "",
                            OrderId = 2,
                            Price = 30000m,
                            ProductId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 5,
                            Notes = "",
                            OrderId = 2,
                            Price = 18000m,
                            ProductId = 17,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 6,
                            Notes = "Belakangan",
                            OrderId = 2,
                            Price = 5000m,
                            ProductId = 14,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 7,
                            Notes = "",
                            OrderId = 3,
                            Price = 22000m,
                            ProductId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 8,
                            Notes = "",
                            OrderId = 3,
                            Price = 15000m,
                            ProductId = 9,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 9,
                            Notes = "Sedikit gula",
                            OrderId = 3,
                            Price = 8000m,
                            ProductId = 16,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 10,
                            Notes = "Tidak pedas",
                            OrderId = 4,
                            Price = 28000m,
                            ProductId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            OrderDetailId = 11,
                            Notes = "",
                            OrderId = 4,
                            Price = 20000m,
                            ProductId = 18,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 12,
                            Notes = "",
                            OrderId = 4,
                            Price = 12000m,
                            ProductId = 10,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 13,
                            Notes = "",
                            OrderId = 4,
                            Price = 5000m,
                            ProductId = 14,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 14,
                            Notes = "Level 3",
                            OrderId = 5,
                            Price = 27000m,
                            ProductId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 15,
                            Notes = "Ekstra saus",
                            OrderId = 5,
                            Price = 15000m,
                            ProductId = 9,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 16,
                            Notes = "",
                            OrderId = 5,
                            Price = 18000m,
                            ProductId = 17,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 17,
                            Notes = "",
                            OrderId = 5,
                            Price = 5000m,
                            ProductId = 14,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 18,
                            Notes = "",
                            OrderId = 6,
                            Price = 24000m,
                            ProductId = 8,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 19,
                            Notes = "",
                            OrderId = 6,
                            Price = 20000m,
                            ProductId = 18,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 20,
                            Notes = "Ekstra coklat",
                            OrderId = 6,
                            Price = 13000m,
                            ProductId = 11,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 21,
                            Notes = "",
                            OrderId = 7,
                            Price = 26000m,
                            ProductId = 7,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 22,
                            Notes = "Kurang gula",
                            OrderId = 7,
                            Price = 5000m,
                            ProductId = 14,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 23,
                            Notes = "",
                            OrderId = 7,
                            Price = 10000m,
                            ProductId = 12,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 24,
                            Notes = "Pedas sedang",
                            OrderId = 8,
                            Price = 25000m,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 25,
                            Notes = "",
                            OrderId = 8,
                            Price = 30000m,
                            ProductId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 26,
                            Notes = "",
                            OrderId = 8,
                            Price = 16000m,
                            ProductId = 13,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 27,
                            Notes = "",
                            OrderId = 8,
                            Price = 8000m,
                            ProductId = 16,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 28,
                            Notes = "Paha",
                            OrderId = 9,
                            Price = 30000m,
                            ProductId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 29,
                            Notes = "",
                            OrderId = 9,
                            Price = 22000m,
                            ProductId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 30,
                            Notes = "",
                            OrderId = 9,
                            Price = 18000m,
                            ProductId = 17,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 31,
                            Notes = "",
                            OrderId = 9,
                            Price = 5000m,
                            ProductId = 14,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 32,
                            Notes = "",
                            OrderId = 10,
                            Price = 28000m,
                            ProductId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 33,
                            Notes = "",
                            OrderId = 10,
                            Price = 15000m,
                            ProductId = 15,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 34,
                            Notes = "",
                            OrderId = 10,
                            Price = 12000m,
                            ProductId = 10,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 35,
                            Notes = "Level 5",
                            OrderId = 11,
                            Price = 27000m,
                            ProductId = 6,
                            Quantity = 2
                        },
                        new
                        {
                            OrderDetailId = 36,
                            Notes = "",
                            OrderId = 11,
                            Price = 15000m,
                            ProductId = 9,
                            Quantity = 2
                        },
                        new
                        {
                            OrderDetailId = 37,
                            Notes = "",
                            OrderId = 11,
                            Price = 5000m,
                            ProductId = 14,
                            Quantity = 2
                        },
                        new
                        {
                            OrderDetailId = 38,
                            Notes = "",
                            OrderId = 11,
                            Price = 20000m,
                            ProductId = 18,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 39,
                            Notes = "Tidak terlalu manis",
                            OrderId = 12,
                            Price = 22000m,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 40,
                            Notes = "",
                            OrderId = 12,
                            Price = 10000m,
                            ProductId = 12,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 41,
                            Notes = "",
                            OrderId = 12,
                            Price = 8000m,
                            ProductId = 16,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 42,
                            Notes = "Tidak pedas",
                            OrderId = 13,
                            Price = 25000m,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 43,
                            Notes = "Tidak pedas",
                            OrderId = 13,
                            Price = 30000m,
                            ProductId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 44,
                            Notes = "",
                            OrderId = 13,
                            Price = 18000m,
                            ProductId = 17,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 45,
                            Notes = "",
                            OrderId = 13,
                            Price = 16000m,
                            ProductId = 13,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 46,
                            Notes = "",
                            OrderId = 13,
                            Price = 5000m,
                            ProductId = 14,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 47,
                            Notes = "Ekstra keju",
                            OrderId = 14,
                            Price = 27000m,
                            ProductId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 48,
                            Notes = "",
                            OrderId = 14,
                            Price = 20000m,
                            ProductId = 18,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 49,
                            Notes = "Ekstra coklat",
                            OrderId = 14,
                            Price = 13000m,
                            ProductId = 11,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 50,
                            Notes = "",
                            OrderId = 15,
                            Price = 22000m,
                            ProductId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 51,
                            Notes = "",
                            OrderId = 15,
                            Price = 26000m,
                            ProductId = 7,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 52,
                            Notes = "",
                            OrderId = 15,
                            Price = 18000m,
                            ProductId = 17,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 53,
                            Notes = "Tanpa bawang",
                            OrderId = 16,
                            Price = 24000m,
                            ProductId = 8,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 54,
                            Notes = "",
                            OrderId = 16,
                            Price = 5000m,
                            ProductId = 14,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 55,
                            Notes = "",
                            OrderId = 16,
                            Price = 12000m,
                            ProductId = 10,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 56,
                            Notes = "",
                            OrderId = 17,
                            Price = 28000m,
                            ProductId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 57,
                            Notes = "Sangat manis",
                            OrderId = 17,
                            Price = 27000m,
                            ProductId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 58,
                            Notes = "",
                            OrderId = 17,
                            Price = 15000m,
                            ProductId = 15,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 59,
                            Notes = "",
                            OrderId = 17,
                            Price = 10000m,
                            ProductId = 12,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 60,
                            Notes = "",
                            OrderId = 18,
                            Price = 25000m,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 61,
                            Notes = "",
                            OrderId = 18,
                            Price = 22000m,
                            ProductId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 62,
                            Notes = "",
                            OrderId = 18,
                            Price = 20000m,
                            ProductId = 18,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 63,
                            Notes = "Paha semua",
                            OrderId = 19,
                            Price = 30000m,
                            ProductId = 3,
                            Quantity = 3
                        },
                        new
                        {
                            OrderDetailId = 64,
                            Notes = "",
                            OrderId = 19,
                            Price = 8000m,
                            ProductId = 16,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 65,
                            Notes = "",
                            OrderId = 19,
                            Price = 5000m,
                            ProductId = 14,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 66,
                            Notes = "Ekstra sambal",
                            OrderId = 20,
                            Price = 22000m,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 67,
                            Notes = "",
                            OrderId = 20,
                            Price = 28000m,
                            ProductId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 68,
                            Notes = "",
                            OrderId = 20,
                            Price = 18000m,
                            ProductId = 17,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 69,
                            Notes = "",
                            OrderId = 20,
                            Price = 13000m,
                            ProductId = 11,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 70,
                            Notes = "",
                            OrderId = 20,
                            Price = 5000m,
                            ProductId = 14,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 71,
                            Notes = "",
                            OrderId = 21,
                            Price = 26000m,
                            ProductId = 7,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 72,
                            Notes = "",
                            OrderId = 21,
                            Price = 5000m,
                            ProductId = 14,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 73,
                            Notes = "Level sedang",
                            OrderId = 22,
                            Price = 27000m,
                            ProductId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 74,
                            Notes = "",
                            OrderId = 22,
                            Price = 24000m,
                            ProductId = 8,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 75,
                            Notes = "",
                            OrderId = 22,
                            Price = 15000m,
                            ProductId = 15,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 76,
                            Notes = "Kurangi garam",
                            OrderId = 23,
                            Price = 22000m,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 77,
                            Notes = "",
                            OrderId = 23,
                            Price = 15000m,
                            ProductId = 9,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 78,
                            Notes = "",
                            OrderId = 23,
                            Price = 18000m,
                            ProductId = 17,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 79,
                            Notes = "",
                            OrderId = 23,
                            Price = 5000m,
                            ProductId = 14,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 80,
                            Notes = "Tidak mau pedas",
                            OrderId = 24,
                            Price = 22000m,
                            ProductId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 81,
                            Notes = "",
                            OrderId = 24,
                            Price = 16000m,
                            ProductId = 13,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 82,
                            Notes = "",
                            OrderId = 25,
                            Price = 25000m,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 83,
                            Notes = "",
                            OrderId = 25,
                            Price = 30000m,
                            ProductId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 84,
                            Notes = "",
                            OrderId = 25,
                            Price = 20000m,
                            ProductId = 18,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailId = 85,
                            Notes = "",
                            OrderId = 25,
                            Price = 10000m,
                            ProductId = 12,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("be.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Makanan Berat",
                            Description = "Nasi goreng ayam plus telur mata sapi & acar",
                            IsAvailable = true,
                            Price = 25000m,
                            ProductName = "Nasi Goreng Spesial"
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Makanan Berat",
                            Description = "Mie goreng khas Jawa, pedas manis dengan kecap",
                            IsAvailable = true,
                            Price = 22000m,
                            ProductName = "Mie Goreng Jawa"
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Makanan Berat",
                            Description = "Ayam bakar bumbu madu legit, disajikan dengan lalapan",
                            IsAvailable = true,
                            Price = 30000m,
                            ProductName = "Ayam Bakar Madu"
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "Makanan Berat",
                            Description = "Nasi uduk dengan ayam goreng, tempe, orek tempe & sambal",
                            IsAvailable = true,
                            Price = 28000m,
                            ProductName = "Nasi Uduk Komplit"
                        },
                        new
                        {
                            ProductId = 5,
                            Category = "Makanan Berat",
                            Description = "Soto ayam kuah bening khas Jawa dengan tauge & soun",
                            IsAvailable = true,
                            Price = 22000m,
                            ProductName = "Soto Ayam Bening"
                        },
                        new
                        {
                            ProductId = 6,
                            Category = "Makanan Berat",
                            Description = "Ayam geprek crispy dengan lelehan keju mozzarella panas",
                            IsAvailable = true,
                            Price = 27000m,
                            ProductName = "Ayam Geprek Keju"
                        },
                        new
                        {
                            ProductId = 7,
                            Category = "Makanan Berat",
                            Description = "Nasi bakar dibungkus daun pisang isi ayam suwir pedas",
                            IsAvailable = true,
                            Price = 26000m,
                            ProductName = "Nasi Bakar Isi Ayam"
                        },
                        new
                        {
                            ProductId = 8,
                            Category = "Makanan Berat",
                            Description = "Mie kuah dengan daging tongseng kambing & sayuran segar",
                            IsAvailable = true,
                            Price = 24000m,
                            ProductName = "Mie Kuah Tongseng"
                        },
                        new
                        {
                            ProductId = 9,
                            Category = "Makanan Ringan",
                            Description = "Kentang goreng renyah seasoning BBQ, disajikan dengan saus",
                            IsAvailable = true,
                            Price = 15000m,
                            ProductName = "Kentang Goreng Crispy"
                        },
                        new
                        {
                            ProductId = 10,
                            Category = "Makanan Ringan",
                            Description = "Cireng aci goreng dengan cocolan bumbu rujak pedas manis",
                            IsAvailable = true,
                            Price = 12000m,
                            ProductName = "Cireng Bumbu Rujak"
                        },
                        new
                        {
                            ProductId = 11,
                            Category = "Makanan Ringan",
                            Description = "Pisang goreng crispy topping coklat & keju leleh",
                            IsAvailable = true,
                            Price = 13000m,
                            ProductName = "Pisang Goreng Coklat"
                        },
                        new
                        {
                            ProductId = 12,
                            Category = "Makanan Ringan",
                            Description = "Tahu goreng crispy disajikan dengan sambal hijau segar",
                            IsAvailable = true,
                            Price = 10000m,
                            ProductName = "Tahu Crispy Sambal Ijo"
                        },
                        new
                        {
                            ProductId = 13,
                            Category = "Makanan Ringan",
                            Description = "Roti bakar tebal dengan selai Nutella & topping susu kental",
                            IsAvailable = true,
                            Price = 16000m,
                            ProductName = "Roti Bakar Nutella"
                        },
                        new
                        {
                            ProductId = 14,
                            Category = "Minuman",
                            Description = "Es teh manis segar, diseduh dari teh pilihan",
                            IsAvailable = true,
                            Price = 5000m,
                            ProductName = "Es Teh Manis"
                        },
                        new
                        {
                            ProductId = 15,
                            Category = "Minuman",
                            Description = "Jus alpukat creamy dengan kerokan es krim vanilla",
                            IsAvailable = true,
                            Price = 15000m,
                            ProductName = "Jus Alpukat Shaked"
                        },
                        new
                        {
                            ProductId = 16,
                            Category = "Minuman",
                            Description = "Jeruk lokal segar diperas langsung, manis asam menyegarkan",
                            IsAvailable = true,
                            Price = 8000m,
                            ProductName = "Es Jeruk Peras"
                        },
                        new
                        {
                            ProductId = 17,
                            Category = "Minuman",
                            Description = "Kopi robusta blend susu segar dengan gula aren pilihan",
                            IsAvailable = true,
                            Price = 18000m,
                            ProductName = "Kopi Susu Gula Aren"
                        },
                        new
                        {
                            ProductId = 18,
                            Category = "Minuman",
                            Description = "Matcha premium Jepang dipadukan susu oat, lembut & gurih",
                            IsAvailable = true,
                            Price = 20000m,
                            ProductName = "Matcha Latte"
                        });
                });

            modelBuilder.Entity("be.Models.OrderDetail", b =>
                {
                    b.HasOne("be.Models.Order", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("be.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("be.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
