// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using be.Data;

#nullable disable

namespace be.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709030000_AddProductImages")]
    partial class AddProductImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("be.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdminId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            PasswordHash = "admin123",
                            Username = "admin123"
                        });
                });

            modelBuilder.Entity("be.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new { ProductId = 1,  ProductName = "Nasi Goreng Spesial",    Category = "Makanan Berat",  Price = 25000m, Description = "Nasi goreng ayam plus telur mata sapi & acar",                     ImageUrl = "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&q=80", IsAvailable = true },
                        new { ProductId = 2,  ProductName = "Mie Goreng Jawa",        Category = "Makanan Berat",  Price = 22000m, Description = "Mie goreng khas Jawa, pedas manis dengan kecap",                   ImageUrl = "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&q=80", IsAvailable = true },
                        new { ProductId = 3,  ProductName = "Ayam Bakar Madu",        Category = "Makanan Berat",  Price = 30000m, Description = "Ayam bakar bumbu madu legit, disajikan dengan lalapan",            ImageUrl = "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=600&q=80", IsAvailable = true },
                        new { ProductId = 4,  ProductName = "Nasi Uduk Komplit",      Category = "Makanan Berat",  Price = 28000m, Description = "Nasi uduk dengan ayam goreng, tempe, orek tempe & sambal",         ImageUrl = "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&q=80", IsAvailable = true },
                        new { ProductId = 5,  ProductName = "Soto Ayam Bening",       Category = "Makanan Berat",  Price = 22000m, Description = "Soto ayam kuah bening khas Jawa dengan tauge & soun",              ImageUrl = "https://images.unsplash.com/photo-1555126634-323283e090fa?w=600&q=80", IsAvailable = true },
                        new { ProductId = 6,  ProductName = "Ayam Geprek Keju",       Category = "Makanan Berat",  Price = 27000m, Description = "Ayam geprek crispy dengan lelehan keju mozzarella panas",          ImageUrl = "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&q=80", IsAvailable = true },
                        new { ProductId = 7,  ProductName = "Nasi Bakar Isi Ayam",    Category = "Makanan Berat",  Price = 26000m, Description = "Nasi bakar dibungkus daun pisang isi ayam suwir pedas",            ImageUrl = "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=600&q=80", IsAvailable = true },
                        new { ProductId = 8,  ProductName = "Mie Kuah Tongseng",      Category = "Makanan Berat",  Price = 24000m, Description = "Mie kuah dengan daging tongseng kambing & sayuran segar",          ImageUrl = "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600&q=80", IsAvailable = true },
                        new { ProductId = 9,  ProductName = "Kentang Goreng Crispy",  Category = "Makanan Ringan", Price = 15000m, Description = "Kentang goreng renyah seasoning BBQ, disajikan dengan saus",       ImageUrl = "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=600&q=80", IsAvailable = true },
                        new { ProductId = 10, ProductName = "Cireng Bumbu Rujak",     Category = "Makanan Ringan", Price = 12000m, Description = "Cireng aci goreng dengan cocolan bumbu rujak pedas manis",         ImageUrl = "https://images.unsplash.com/photo-1606914707244-e398ddb0e370?w=600&q=80", IsAvailable = true },
                        new { ProductId = 11, ProductName = "Pisang Goreng Coklat",   Category = "Makanan Ringan", Price = 13000m, Description = "Pisang goreng crispy topping coklat & keju leleh",                 ImageUrl = "https://images.unsplash.com/photo-1528975604071-b4dc52a2d18c?w=600&q=80", IsAvailable = true },
                        new { ProductId = 12, ProductName = "Tahu Crispy Sambal Ijo", Category = "Makanan Ringan", Price = 10000m, Description = "Tahu goreng crispy disajikan dengan sambal hijau segar",           ImageUrl = "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&q=80", IsAvailable = true },
                        new { ProductId = 13, ProductName = "Roti Bakar Nutella",     Category = "Makanan Ringan", Price = 16000m, Description = "Roti bakar tebal dengan selai Nutella & topping susu kental",      ImageUrl = "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=600&q=80", IsAvailable = true },
                        new { ProductId = 14, ProductName = "Es Teh Manis",           Category = "Minuman",        Price = 5000m,  Description = "Es teh manis segar, diseduh dari teh pilihan",                    ImageUrl = "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&q=80", IsAvailable = true },
                        new { ProductId = 15, ProductName = "Jus Alpukat Shaked",     Category = "Minuman",        Price = 15000m, Description = "Jus alpukat creamy dengan kerokan es krim vanilla",               ImageUrl = "https://images.unsplash.com/photo-1551023916-61b31b05de9b?w=600&q=80", IsAvailable = true },
                        new { ProductId = 16, ProductName = "Es Jeruk Peras",         Category = "Minuman",        Price = 8000m,  Description = "Jeruk lokal segar diperas langsung, manis asam menyegarkan",      ImageUrl = "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=600&q=80", IsAvailable = true },
                        new { ProductId = 17, ProductName = "Kopi Susu Gula Aren",    Category = "Minuman",        Price = 18000m, Description = "Kopi robusta blend susu segar dengan gula aren pilihan",          ImageUrl = "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&q=80", IsAvailable = true },
                        new { ProductId = 18, ProductName = "Matcha Latte",           Category = "Minuman",        Price = 20000m, Description = "Matcha premium Jepang dipadukan susu oat, lembut & gurih",        ImageUrl = "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=600&q=80", IsAvailable = true }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
